language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git valgrind
install:
  - make getexternals
  - make -C libcollect
  - make -C lemon
script:
  - make test
