site_name: Event Compiler
site_author: Andreas Pfohl & Robert Heumüller
repo_url: https://github.com/compiler-dept/event-compiler
copyright: Copyright &copy; 2015 by <a href="https://github.com/apfohl">Andreas Pfohl</a> and <a href="https://github.com/rheum">Robert Heumüller</a>.
